#! /bin/bash

# creates yearly directories in $OUTDIR
# TMP dirs are supposed already generated by var_aggregator.py

INPUTDIR_1=/gpfs/scratch/userexternal/gbolzon0/REA_24/TEST_22/wrkdir/MODEL/AVE_FREQ_1
INPUTDIR_2=/gpfs/scratch/userexternal/gcoidess/POSTPROC_REA_24/TEST22/AVE_FREQ_1/TMP
OUTDIR=/gpfs/scratch/userexternal/gbolzon0/REA_24/TEST_11/wrkdir/POSTPROC/ARCHIVE/AVE_FREQ_1

mkdir -p $OUTDIR

for year in `seq 1999 2002 `; do
   mkdir $OUTDIR/$year
   cd $OUTDIR/$year
   for I in $INPUTDIR_1/ave.${year}* ; do
      ln -s $I
   done
   for I in $INPUTDIR_2/ave.${year}* ; do
      ln -s $I
   done
done


INPUTDIR_1=/gpfs/scratch/userexternal/gbolzon0/REA_24/TEST_22/wrkdir/MODEL/AVE_FREQ_2
INPUTDIR_2=/gpfs/scratch/userexternal/gcoidess/POSTPROC_REA_24/TEST22/AVE_FREQ_2/TMP
OUTDIR=/gpfs/scratch/userexternal/gbolzon0/REA_24/TEST_11/wrkdir/POSTPROC/ARCHIVE/AVE_FREQ_2

mkdir -p $OUTDIR

for year in `seq 1999 2002 `; do
   mkdir $OUTDIR/$year
   cd $OUTDIR/$year
   for I in $INPUTDIR_1/ave.${year}* ; do
      ln -s $I
   done
   for I in $INPUTDIR_2/ave.${year}* ; do
      ln -s $I
   done
done

