#!/bin/bash

#SBATCH --job-name=prod_daily
#SBATCH -N 5
#SBATCH --ntasks-per-node=25
#SBATCH --time=20:00:00
#SBATCH --mem=115gb
#SBATCH --account=OGS_prod_0
#SBATCH -p gll_meteo_prod
#SBATCH --dependency=afterany:8127755
#SBATCH --qos=gll_qos_meteoogs

cd $SLURM_SUBMIT_DIR

module purge
module load profile/base
module load intel/pe-xe-2018--binary intelmpi/2018--binary
module load autoload
module load hdf5/1.8.18--intel--pe-xe-2018--binary netcdf/4.6.1--intel--pe-xe-2018--binary
module load mpi4py/3.0.0--intelmpi--2018--binary
source /gpfs/work/OGS20_PRACE_P/COPERNICUS/py_env_2.7.12/bin/activate
export PYTHONPATH=$PYTHONPATH:/gpfs/work/OGS20_PRACE_P/COPERNICUS/bit.sea


. ../profile.inc
#daily

INPUTDIR=/gpfs/scratch/userexternal/gbolzon0/V7C/TEST_07/wrkdir/MODEL/AVE_FREQ_1/

NEW_INPUT=/gpfs/scratch/userexternal/gcoidess/PRODOTTI_NRT/all_files_daily
mkdir -p $NEW_INPUT

INPUT_AGGREGATE=/gpfs/scratch/userexternal/gcoidess/TRANSITION_AVESCAN/OUTPUT/AVE_FREQ_1/TMP/

HERE=$PWD

cd $NEW_INPUT
for i in `ls ${INPUTDIR}/*.nc`
  do
    ln -fs $i
  done

#rm -rf ave.2021*

for i in `ls ${INPUT_AGGREGATE}/*.nc`
  do
    ln -fs $i
  done

OUTPUTDIR=/gpfs/scratch/userexternal/gcoidess/PRODOTTI_NRT/prodotti_nrt/daily/
MASKFILE=/gpfs/scratch/userexternal/gbolzon0/V7C/TEST_07/wrkdir/MODEL/meshmask.nc
#daily

mkdir -p $OUTPUTDIR

cd $NEW_INPUT

if [ 1 == 0 ]; then
for Y in 2019 2020
do
    for M in 01 02 03 04 05 06 07 08 09 10 11 12
    do
        ls ave.$Y$M*N1p.nc | cut -c 5-12 >> $HERE/timelist_daily_NRT
    done
done

for Y in 2021
 do
      for M in 01 02 03 
      do
          ls ave.$Y$M*N1p.nc | cut -c 5-12 >> $HERE/timelist_daily_NRT
      done
 done
fi
if [ 1 == 0 ]; then
ls ave.*N1p.nc | cut -c 5-12 > $HERE/timelist_daily_NRT

cd $SLURM_SUBMIT_DIR
my_prex_or_die "mpirun python prodotti_copernicus.py -i $NEW_INPUT -o $OUTPUTDIR -t timelist_daily_NRT -m $MASKFILE -b 20210323 --tr daily  -d an"

fi
#monthly
cd $SLURM_SUBMIT_DIR
HERE=$PWD

INPUTDIR=/gpfs/scratch/userexternal/gcoidess/TRANSITION_AVESCAN/OUTPUT/MONTHLY/monthly_ave/
OUTPUTDIR=/gpfs/scratch/userexternal/gcoidess/PRODOTTI_NRT/prodotti_nrt/monthly/


mkdir -p $OUTPUTDIR

cd $INPUTDIR

if [ 1 == 0 ]; then
for Y in 2019 2020 2021
do
    ls ave.$Y*N1p.nc | cut -c 5-12 >> $HERE/timelist_monthly_NRT
done

for Y in 2021
 do
      ls ave.2021*N1p.nc | cut -c 5-12 >> $HERE/timelist_monthly_NRT
 done
fi

ls ave.*N1p.nc | cut -c 5-12 > $HERE/timelist_monthly_NRT


cd $SLURM_SUBMIT_DIR
my_prex_or_die "mpirun python prodotti_copernicus.py -i $INPUTDIR -o $OUTPUTDIR -t timelist_monthly_NRT -m $MASKFILE -b 20210323 --tr monthly -d an "

exit 0
